@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Oct 22 16:49:22 +0200 2019
REM SW Build 2644227 on Wed Sep  4 09:45:24 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim TB_opgave_1_behav -key {Behavioral:sim_1:Functional:TB_opgave_1} -tclbatch TB_opgave_1.tcl -view C:/Users/yorbe/OneDrive/Bureaublad/opgave_1/TB_opgave_1_behav.wcfg -log simulate.log"
call xsim  TB_opgave_1_behav -key {Behavioral:sim_1:Functional:TB_opgave_1} -tclbatch TB_opgave_1.tcl -view C:/Users/yorbe/OneDrive/Bureaublad/opgave_1/TB_opgave_1_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
